services:
  - type: web
    name: gpt-studio
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.11.0
      - key: VITE_API_BASE_URL
        value: /api
      - key: APP_MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CHROMA_API_KEY
        sync: false
      - key: CHROMA_TENANT
        sync: false
      - key: CHROMA_DATABASE
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: OPENROUTER_AI_ENDPOINT
        sync: false
      - key: OPENROUTER_CHAT_MODEL_NAME
        sync: false
      - key: AZURE_AI_API_KEY
        sync: false
      - key: AZURE_AI_ENDPOINT
        sync: false
      - key: EMBEDDING_MODEL_NAME
        sync: false
      - key: CHAT_MODEL_NAME
        sync: false
      - key: FAST_MODEL_NAME
        sync: false
